import * as anchor from "@coral-xyz/anchor";
import type { Provider } from "@coral-xyz/anchor";
import idl from "./generated/goalpost.idl.json";
import type { Goalpost } from "./generated/goalpost.js";

/**
 * Builds a fully-typed `Program<Goalpost>` from the real IDL generated by
 * `anchor build` in CI (see `.github/workflows/anchor-ci.yml` and
 * `docs/ARCHITECTURE.md` - there is no local Anchor toolchain in this repo,
 * so this generated IDL is the single source of truth, not a hand-written
 * copy). Every SDK function that talks to the program takes this typed
 * `Program<Goalpost>`, so account fetches (`program.account.market.fetch`)
 * and instruction builders are type-checked against the real on-chain
 * interface, not `anchor.Program<Idl>`'s untyped fallback.
 */
export function loadProgram(provider: Provider): anchor.Program<Goalpost> {
  return new anchor.Program<Goalpost>(idl as Goalpost, provider);
}

export type { Goalpost };
